### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by LeviMester** [justricsi/www.ballonos.hu---weboldal#11]
szar a footer , több szín, hol magas, hol alacsony

**Comment by justricsi** [comment]
Javítva a hiba, viszont a 8-as menün továbbra is fennáll a probléma! Agylerobbanás miatt pihentetem kicsit.
![image](https://user-images.githubusercontent.com/13610714/34532502-9ec32998-f0b6-11e7-9de9-588ba7bb5d48.png)

**Comment by justricsi** [comment]
megoldva
