### ISSUE TITLE
KÉPCSERE

### ISSUE THREAD

**Issue by LeviMester** [justricsi/www.ballonos.hu---weboldal#15]
header kép cseréje 
oldalt emese másik oldalon csszentkirályi logója

**Comment by justricsi** [comment]
A fejléc képe kicserélve a két formátumura. Az alábbi linken csekkolható!

![header3](https://user-images.githubusercontent.com/13610714/34529030-fc840dd8-f0aa-11e7-9a07-9d68c8092548.png)
