### ISSUE TITLE
Baloldali div és a tartalom div mérete

### ISSUE THREAD

**Issue by justricsi** [justricsi/www.ballonos.hu---weboldal#6]
Utána néztem de elég szar megoldásokat találtam, javítani kéne, hogy a menü és a tartalom div egyforma nagyságú legyen. Mert jelen helyzetben a menü akkora amennyi tartalom van benne és ugyan ez van a tartalom div-el is.
Hiba a képen:
![image](https://user-images.githubusercontent.com/13610714/34425120-85c7bd64-ec29-11e7-8086-7025f02f940d.png)

**Comment by LeviMester** [comment]
megoldva
